; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=fero %s -o - | FileCheck %s

define i16 @test(i16* %a) {
entry:
  %0 = load i16, i16* %a
  ret i16 %0
}
