; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=fero-fero-none-eabi %s -o - | FileCheck --check-prefix=CHECK %s

define i16 @test(i16* %a) {
entry:
  %0 = load i16, i16* %a
  ret i16 %0
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
